### ISSUE TITLE
Plugin is loaded - doesnt show in Homekit

### ISSUE THREAD

**Issue by Richardmarobert** [petergerdes/homebridge-anna#1]
Thanks for the plugin! I've installed it according to instructions, altered the config.json and I notice the plugin beeing loaded and the accessory registered, but the accessory doesn't show in my homekit. Maybe I am not using the correct credentials, but then again it's not showing any errors in when running **journalctl -u homebridge**.

I currently have the fibaro plugin installed and that works flawlessly. 

My config.json looks like this: 

 
```
"accessories": [
                {
                "accessory": "Thermostat",
                "name": "[smile with additional unqiue number]",
                "name": "Thermostat",
                "ip": "[local ip address]",
                "password": "[password I use for my Anna]",
                "maxTemp": "24",
                "minTemp": "15",
                }
    ]

````
All help would be appreciated.

**Comment by petergerdes** [comment]
I see that you have declared 'name' twice, 1 should be more then enough!

```
{
 "accessory": "Thermostat",
"name": "Thermostat",
"ip": "[local ip address]",
"password": "[password I use for my Anna]",
"maxTemp": "24",
 "minTemp": "15"
}
```

Let me know if this helps!

**Comment by Richardmarobert** [comment]
I've changed it accordingly, using one name. Tried 'Smile' instead of 'Thermostat', every change followed by a reboot; but without result :/

**Comment by petergerdes** [comment]
Do you have any output in the homebridge log file? If you're using Linux it's probably located at /var/log/homebridge.log. It should report somewhere that it can't connect.

**Comment by Richardmarobert** [comment]
hmmm. No log with such name, at all. (used find -name *.log  or homebridge.*) The "name" and "Password" that are used in the config.json should match the ones used when opening the webpage of the Smile?

**Comment by petergerdes** [comment]
The username is always 'smile' in the plugin's code, the name you enter in the config.json is purely how it wel get exposed to Homekit. The password should indeed be the one that you use for Anna's webview. Do you have any more details about your setup? How is homebridge installed? Which node version are you running?

What output do you see if you run:
`DEBUG=* ./{pathtoyourinstallation}/homebridge -I`

**Comment by Richardmarobert** [comment]
this is in the output - also in journalctl. I use node version 9.9.0. I have homebridge running as a service from systemd, so it starts automatically at bootup. Removeing accessories and persist didnt help

`Jul 09 19:45:01 raspberrypi homebridge[261]: [2019-7-9 19:45:01] ---
Jul 09 19:45:07 raspberrypi homebridge[261]: [2019-7-9 19:45:07] Loaded plugin: homebridge-anna
Jul 09 19:45:07 raspberrypi homebridge[261]: [2019-7-9 19:45:07] Registering accessory 'homebridge-anna-thermostat.Thermostat'
Jul 09 19:45:07 raspberrypi homebridge[261]: [2019-7-9 19:45:07] ---
`

**Comment by petergerdes** [comment]
So after registering there is not more output? Can you stop the homebridge process by hand and try running 

`DEBUG=* ./{pathtoyourinstallation}/homebridge -I`

**Comment by Richardmarobert** [comment]
Found the problem - I think with copy paste something went wrong. re-typed the data and it loads the accessory now, too. But, when using the Anna accessory the homekit doesn't respond anymore.  All accessories are 'unavailable' and this remains until I remove the accessory from the config.json

`Jul 12 21:07:33 raspberrypi homebridge[237]: [2019-7-12 21:07:33] [Thermostaat] getCurrentTemperature from Anna on: 192.168.2.1
Jul 12 21:07:33 raspberrypi homebridge[237]: [2019-7-12 21:07:33] [Thermostaat] getCurrentTargetTemperature from Anna on: 192.168.2.1
Jul 12 21:07:34 raspberrypi homebridge[237]: _getMeasure() -> this.status = online
Jul 12 21:07:35 raspberrypi homebridge[237]: _getTarget() -> this.status = online
Jul 12 21:07:36 raspberrypi homebridge[237]: [2019-7-12 21:07:36] [Thermostaat] getCurrentTemperature from Anna on: 192.168.2.1
Jul 12 21:07:36 raspberrypi homebridge[237]: [2019-7-12 21:07:36] [Thermostaat] getCurrentTargetTemperature from Anna on: 192.168.2.1
Jul 12 21:07:37 raspberrypi homebridge[237]: _getMeasure() -> this.status = online
Jul 12 21:07:38 raspberrypi homebridge[237]: _getTarget() -> this.status = online
Jul 12 21:07:39 raspberrypi homebridge[237]: [2019-7-12 21:07:39] [Thermostaat] getCurrentTemperature from Anna on: 192.168.2.1
Jul 12 21:07:39 raspberrypi homebridge[237]: [2019-7-12 21:07:39] [Thermostaat] getCurrentTargetTemperature from Anna on: 192.168.2.1
Jul 12 21:07:40 raspberrypi homebridge[237]: _getTarget() -> this.status = online
Jul 12 21:07:41 raspberrypi homebridge[237]: _getMeasure() -> this.status = online
`

**Comment by Richardmarobert** [comment]
yes, this is just  a snippet. Homebridge is registering the accessories quite ok, but when the Anna plug begins requiring the information that's the only thing that happens. Even set the timer in index.js from 3000 to 60000 but didn't work out. 
I'll try run the debug tomorrow.

**Comment by petergerdes** [comment]
When statusses get back with 'online' by Anna, then in theory it should work.. Only thing it does then is store the value it got back and when Homekit is asking for it then returning that value.

A while ago I wrote a gist with my current setup and how to install everything (it's basically for myself to keep track of what I did to get stuff up and running), might be useful: https://gist.github.com/petergerdes/422239985cdcc594ab2d74a4d289c66f

**Comment by Richardmarobert** [comment]
Got my Anna working on Homekit - appearantly Raspberry PI was too busy handling the communication. A bit more powerfull server solved it. Today I ran into a problem that my Smile suddenly crashed though; only after disconnecting the homekit it came back online again. Is there any parameter in the config I can adjust the time between each request to Anna from the plugin?

**Comment by petergerdes** [comment]
Nice! It does the request every 3 seconds. I could make it configurable for you if you want? I switched to Home-Assistant myself and am much happier with how that all works!

**Comment by petergerdes** [comment]
I went ahead and made it configurable! But as I don’t use it myself anymore I cannot test, so haven’t pushed it to NPM yet. Are you able to test it by installing though Github?

You can add `"interval": "5000"`, for a 5 second interval.

Latest commit to make it configurable: https://github.com/petergerdes/homebridge-anna/commit/f948fc09e5a1a4f749ae399904905f6401d86bf6
